export const REMOVE_POKEDEX = 'REMOVE_POKEDEX';
export const POKEMON_LOAD = 'POKEMON_LOAD';
export const POKEMON_LOAD_SUCCESS = 'POKEMON_LOAD_SUCCESS';
export const POKEMON_LOAD_FAIL = 'POKEMON_LOAD_FAIL';